using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Xamarin.Forms;

namespace UpcomingMovies.Converter
{
    public class LanguageConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var language = (string)value;

            switch (language)
            {
                case "aa":
                    return "Afar";
                case "af":
                    return "Afrikaans";
                case "ak":
                    return "Akan";
                case "an":
                    return "Aragonese";
                case "as":
                    return "Assamese";
                case "av":
                    return "Avaric";
                case "ae":
                    return "Avestan";
                case "ay":
                    return "Aymara";
                case "az":
                    return "Azerbaijani";
                case "ba":
                    return "Bashkir";
                case "bm":
                    return "Bambara";
                case "bi":
                    return "Bislama";
                case "bo":
                    return "Tibetan";
                case "br":
                    return "Breton";
                case "ca":
                    return "Catalan";
                case "cs":
                    return "Czech";
                case "ce":
                    return "Chechen";
                case "cu":
                    return "Slavic";
                case "cv":
                    return "Chuvash";
                case "kw":
                    return "Cornish";
                case "co":
                    return "Corsican";
                case "cr":
                    return "Cree";
                case "cy":
                    return "Welsh";
                case "da":
                    return "Danish";
                case "de":
                    return "German";
                case "dv":
                    return "Divehi";
                case "dz":
                    return "Dzongkha";
                case "eo":
                    return "Esperanto";
                case "et":
                    return "Estonian";
                case "eu":
                    return "Basque";
                case "fo":
                    return "Faroese";
                case "fj":
                    return "Fijian";
                case "fi":
                    return "Finnish";
                case "fr":
                    return "French";
                case "fy":
                    return "Frisian";
                case "ff":
                    return "Fulah";
                case "gd":
                    return "Gaelic";
                case "ga":
                    return "Irish";
                case "gl":
                    return "Gallegan";
                case "gv":
                    return "Manx";
                case "gn":
                    return "Guarani";
                case "gu":
                    return "Gujarati";
                case "ht":
                    return "Haitian; Haitian Creole";
                case "ha":
                    return "Huasa";
                case "sh":
                    return "Serbo-Croatian";
                case "hz":
                    return "Herero";
                case "ho":
                    return "Hiri Motu";
                case "hr":
                    return "Croatian";
                case "hu":
                    return "Hungarian";
                case "ig":
                    return "Igbo";
                case "io":
                    return "Ido";
                case "ii":
                    return "Yi";
                case "iu":
                    return "Inuktitut";
                case "ie":
                    return "Interlingue";
                case "ia":
                    return "Interlingua";
                case "id":
                    return "Indonesian";
                case "ik":
                    return "Inupiaq";
                case "is":
                    return "Icelandic";
                case "it":
                    return "Italian";
                case "jv":
                    return "javanese";
                case "ja":
                    return "Japanese";
                case "kl":
                    return "Kalaallisut";
                case "Kn":
                    return "Kannada";
                case "ks":
                    return "Kashmiri";
                case "kr":
                    return "Kanuri";
                case "kk":
                    return "Kazakh";
                case "km":
                    return "Khmer";
                case "ki":
                    return "Kikuyu";
                case "rw":
                    return "Kinyarwanda";
                case "ky":
                    return "Kirghiz";
                case "kv":
                    return "Komi";
                case "kg":
                    return "Kongo";
                case "ko":
                    return "Korean";
                case "kj":
                    return "Kuanyama";
                case "ku":
                    return "Kurdish";
                case "lo":
                    return "Lao";
                case "la":
                    return "Latin";
                case "lv":
                    return "Latvian";
                case "li":
                    return "Limburgish";
                case "ln":
                    return "Lingala";
                case "lt":
                    return "Lithuanian";
                case "lb":
                    return "Letzeburgesch";
                case "lu":
                    return "Luba-Katanga";
                case "lg":
                    return "Ganda";
                case "mh":
                    return "Marshall";
                case "ml":
                    return "Malayalam";
                case "mr":
                    return "Marathi";
                case "mg":
                    return "Malagasy";
                case "mt":
                    return "Maltese";
                case "mo":
                    return "Moldavian";
                case "mn":
                    return "Mongolian";
                case "mi":
                    return "Maori";
                case "ms":
                    return "Malay";
                case "my":
                    return "Burmese";
                case "na":
                    return "Nauru";
                case "nv":
                    return "Navajo";
                case "nr":
                case "nd":
                    return "Ndebele";
                case "ng":
                    return "Ndonga";
                case "ne":
                    return "Nepali";
                case "nl":
                    return "Dutch";
                case "nn":
                    return "Norwegian Nynorsk";
                case "nb":
                    return "Norwegian Bokmål";
                case "no":
                    return "Norwegian";
                case "ny":
                    return "Chichewa; Nyanja";
                case "oc":
                    return "Occitan";
                case "oj":
                    return "Ojibwa";
                case "or":
                    return "Oriya";
                case "om":
                    return "Oromo";
                case "os":
                    return "Ossetian; Ossetic";
                case "pi":
                    return "Pali";
                case "pl":
                    return "Polish";
                case "pt":
                    return "Portuguese";
                case "qu":
                    return "Quechua";
                case "rm":
                    return "Raeto-Romance";
                case "ro":
                    return "Romanian";
                case "rn":
                    return "Rundi";
                case "ru":
                    return "Russian";
                case "sg":
                    return "Sango";
                case "sa":
                    return "Sanskrit";
                case "si":
                    return "Sinhalese";
                case "sk":
                    return "Slovak";
                case "sl":
                    return "Slovenian";
                case "se":
                    return "Northern Sami";
                case "sm":
                    return "Samoan";
                case "sn":
                    return "Shona";
                case "sd":
                    return "Sindhi";
                case "so":
                    return "Somali";
                case "st":
                    return "Sotho";
                case "es":
                    return "Spanish";
                case "sq":
                    return "Albanian";
                case "sc":
                    return "Sardinian";
                case "sr":
                    return "Serbian";
                case "ss":
                    return "Swati";
                case "su":
                    return "Sundanese";
                case "sw":
                    return "Swahili";
                case "sv":
                    return "Swedish";
                case "ty":
                    return "Tahitian";
                case "ta":
                    return "Tamil";
                case "tt":
                    return "Tatar";
                case "te":
                    return "Telugu";
                case "tg":
                    return "Tajik";
                case "tl":
                    return "Tagalog";
                case "th":
                    return "Thai";
                case "ti":
                    return "Tigrinya";
                case "to":
                    return "Tonga";
                case "tn":
                    return "Tswana";
                case "ts":
                    return "Tsonga";
                case "tk":
                    return "Turkmen";
                case "tr":
                    return "Turkish";
                case "tw":
                    return "Twi";
                case "ug":
                    return "Uighur";
                case "uk":
                    return "Ukrainian";
                case "ur":
                    return "Urdu";
                case "uz":
                    return "Uzbek";
                case "ve":
                    return "Venda";
                case "vi":
                    return "Vietnamese";
                case "vo":
                    return "Volapük";
                case "wa":
                    return "Walloon";
                case "wo":
                    return "Wolof";
                case "xh":
                    return "Xhosa";
                case "yi":
                    return "Yiddish";
                case "za":
                    return "Zhuang";
                case "zu":
                    return "Zulu";
                case "ab":
                    return "Abkhazian";
                case "zh":
                    return "Mandarin";
                case "ps":
                    return "Pushto";
                case "am":
                    return "Amharic";
                case "ar":
                    return "Arabic";
                case "bg":
                    return "Bulgarian";
                case "cn":
                    return "Cantonese";
                case "mk":
                    return "Macedonian";
                case "el":
                    return "Greek";
                case "fa":
                    return "Persian";
                case "he":
                    return "Hebrew";
                case "hi":
                    return "Hindi";
                case "hy":
                    return "Armenian";
                case "en":
                    return "English";
                case "ee":
                    return "Ewe";
                case "ka":
                    return "Georgian";
                case "pa":
                    return "Punjabi";
                case "bn":
                    return "Bengali";
                case "bs":
                    return "Bosnian";
                case "ch":
                    return "Chamorro";
                case "be":
                    return "Belarusian";
                case "xx":
                default:
                    return language;
            }
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
